### ISSUE TITLE
Using filters to prune out irrelevant data

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/CS-GO-Professionals#1]
The url from [hltv.org](https://hltv.org) lists all of the csgo players, even from tier 3-4 + which aren't quite relevant when compared to higher tier professionals.

It'd be better if a ranking filter is added to prune the dataset somewhat.

**Comment by aarshgoel1502** [comment]
i want to work on this issue. kindly assign me this issue.

**Comment by Chirag-01** [comment]
@sbk2k1 me and @aarshgoel1502 are working together for this issue

**Comment by sbk2k1** [comment]
Sure!
