### ISSUE TITLE
prostats.gg

### ISSUE THREAD

**Issue by sbk2k1** [DSCKGEC/CS-GO-Professionals#19]
We can create a Website called prostats.gg using all the artifacts from different EDAs.

It will be an interactive read-only website where users can see stats about different players and related graphs and images.

**Comment by sbk2k1** [comment]
Please feel free to create issues and discuss the requirements for this project.

**Comment by affaannn** [comment]
can I work on this issue??

**Comment by affaannn** [comment]
> Please feel free to create issues and discuss the requirements for this project.

Can I work on this issue??

**Comment by affaannn** [comment]
> We can create a Website called prostats.gg using all the artifacts from different EDAs.
> 
> 
> 
> It will be an interactive read-only website where users can see stats about different players and related graphs and images.
> 
> 

Can I work on this issue??

**Comment by sbk2k1** [comment]
sure @affaannn! create issues and start working.

**Comment by affaannn** [comment]
> sure @affaannn! create issues and start working.

Okay Thanks!
I am creating a dashboard board for the same issue(#19)
Plzz assign me

**Comment by sbk2k1** [comment]
@affaannn since this is a bigger issue, please create an issue for the feature you want to add and @ me there. I'll assign that to you.
