### ISSUE TITLE
Complete the Scraping Notebook

### ISSUE THREAD

**Issue by sbk2k1** [DSCKGEC/CS-GO-Professionals#2]
Steps:
1. Go to 'scraping notebook.ipynb'
2. Complete unfinished code and Save it as "Scrape_Data.csv"

**Comment by Sanjana-Srinidhi** [comment]
Hey! I would like to work on this issue. Kindly assign it to me. Thank you.

**Comment by sbk2k1** [comment]
Great to see you here @Sanjana-Srinidhi. I've assigned the issue to you. Good Luck.

**Comment by Arg-10** [comment]
Please assign the issue to me.
