### ISSUE TITLE
Create Columns for Kills and Deaths for each player

### ISSUE THREAD

**Issue by sbk2k1** [DSCKGEC/CS-GO-Professionals#3]
From K/D ratio and K-D difference, try to come up with separate columns from Kills and Deaths.

**Comment by KewlShubh** [comment]
Hi, I would like to work on this issue. Kindly assign it to me

**Comment by DravidVaishnav** [comment]
Can I work on this issue?

**Comment by sbk2k1** [comment]
Sure @DravidVaishnav !

**Comment by aarshgoel1502** [comment]
I want to make a PR. Assign me this issue.

**Comment by sbk2k1** [comment]
@DravidVaishnav any updates? I'm assigning this to both you and @aarshgoel1502

**Comment by DravidVaishnav** [comment]
Task is done please check my PR @sbk2k1

**Comment by sbk2k1** [comment]
@DravidVaishnav sorry for not noticing earlier. Good Work!

**Comment by DravidVaishnav** [comment]
No worries, thanks for merging @sbk2k1
