### ISSUE TITLE
Perform EDA to find best players

### ISSUE THREAD

**Issue by sbk2k1** [DSCKGEC/CS-GO-Professionals#4]
Perform EDA to find the top 10 best players according to:
1. HLTV Rating
2. K/D Ratio

Create different .csv files for the tasks and save them inside EDA and Feature Engineering Directory

**Comment by RohanHBTU** [comment]
May I work on this issue?

**Comment by sbk2k1** [comment]
@RohanHBTU it's great to see you here. Absolutely!

**Comment by aarshgoel1502** [comment]
I want to make a PR. kindly assign me this issue.

**Comment by sbk2k1** [comment]
Sure @aarshgoel1502 !
