### ISSUE TITLE
Most maps and rounds played

### ISSUE THREAD

**Issue by sbk2k1** [DSCKGEC/CS-GO-Professionals#6]
Create two different csv files in the EDA and Feature Engineering directory containing the top 10 of the following:
1. Most maps played
2. Most Rounds played

Check how they correlate and try to derive conclusions. What can be some reasons that these two lists are not the same if they aren't?

**Comment by SWITCHin2** [comment]
I would like to try to work on this.

**Comment by sbk2k1** [comment]
It's great to see you want to work here! But I would like to know the approach you will take, to find the conclusions.

**Comment by SWITCHin2** [comment]
Kind of confused as I am a beginner. Some advice would help me to accomplish the workk

**Comment by sbk2k1** [comment]
Being a beginner is not something that's the problem. You need some CSGO Context. Like some maps are heavily one-sided. It can also, but not sure, say how good a player is at closing out a certain map and not choking. A fair bit of CSGO knowledge is needed.

**Comment by A1zenSousuke** [comment]
@sbk2k1 can you assign this issue to me?

**Comment by sbk2k1** [comment]
@kpratik1929 yes I can, but first I need to understand the approach you will take, to find the conclusions and/or the correlations.

**Comment by kpratik1929** [comment]
@sbk2k1 I will first get the TOP 10 from data sets for both condition and save it . The last part is little confusing for me , cause you want the correlation between both Top 10 data sets. I think I will go with K/D ratio and kill death difference. And ofc try some other things to see whether I can get some relations or not.

**Comment by kpratik1929** [comment]
Heatmap is better for showing correlation right?

**Comment by A1zenSousuke** [comment]
@sbk2k1 I think Most Maps and Most Rounds play will be related to KD ratio . I will try it with other attributes as well and visualise on heatmap for correlation.

**Comment by sbk2k1** [comment]
Ok go ahead!

**Comment by A1zenSousuke** [comment]
![csgo](https://user-images.githubusercontent.com/30045569/182071429-07d2afdd-5d97-447e-b1f6-9d7197da3d03.png)
@sbk2k1 is this the result you want for most maps and most rounds?

**Comment by sbk2k1** [comment]
Yes that's it. But try you provide some context or try to come up with something as to why the lists of players aren't the same.

**Comment by A1zenSousuke** [comment]
![csgo_2](https://user-images.githubusercontent.com/30045569/182095649-2e506370-cb79-4bc9-9230-5cbc922f3214.png)
@sbk2k1 is this the correlation you wanted?

**Comment by sbk2k1** [comment]
Yeah @kpratik1929 that's fine. You can also write/lay down some context about your results if are into the game.

**Comment by A1zenSousuke** [comment]
@sbk2k1 ok I'll do that
