### ISSUE TITLE
Use 2 step web scrapping to find details of Top players in 2021

### ISSUE THREAD

**Issue by Chirag-01** [DSCKGEC/CS-GO-Professionals#9]
I am using this web site
https://www.playerauctions.com/csgo-stats/ranking/
To find further details I will visit each player link
https://www.playerauctions.com//csgo-stats/76561198390156480/
We can find details about KDR ,headshots Total hours,Kills ,Accuracy ,Name, Time,Total Kills,Total Wins 
We can also go for additional level of details with total money earned etc

**Comment by sbk2k1** [comment]
Good research on the website! Best of luck with the issue.

**Comment by sbk2k1** [comment]
Hey, @Chirag-01 sorry for the late reply! But are you sure all the players mentioned in the CSV file are professionals, there are a lot of non-professional names popping up? And the website is for selling accounts so the stats aren't the most accurate. Could you look into that and inform accordingly

**Comment by sbk2k1** [comment]
I'll be closing this issue since the websites are not accurate on the professional aspect of CS.
